#ifndef _ZCFG_RDM_OID_H
#define _ZCFG_RDM_OID_H
#define RDM_OID_DEVICE                           0 	/*Device*/
#define RDM_OID_SERVICE                          108	/*Device.Services*/
#define RDM_OID_VOICE_SRV                        144	/*Device.Services.VoiceService.i*/
#define RDM_OID_VOICE_CAPB                       228	/*Device.Services.VoiceService.i.Capabilities*/
#define RDM_OID_VOICE_CAPB_SIP                   1032	/*Device.Services.VoiceService.i.Capabilities.SIP*/
#define RDM_OID_VOICE_CAPB_MGCP                  1332	/*Device.Services.VoiceService.i.Capabilities.MGCP*/
#define RDM_OID_VOICE_CAPB_H323                  1392	/*Device.Services.VoiceService.i.Capabilities.H323*/
#define RDM_OID_VOICE_CAPB_CODEC                 1476	/*Device.Services.VoiceService.i.Capabilities.Codec.i*/
#define RDM_OID_VOICE_PROF                       1656	/*Device.Services.VoiceService.i.VoiceProfile.i*/
#define RDM_OID_VOICE_PROF_SRV_PRO_INFO          2580	/*Device.Services.VoiceService.i.VoiceProfile.i.ServiceProviderInfo*/
#define RDM_OID_VOICE_PROF_SIP                   2712	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP*/
#define RDM_OID_VOICE_PROF_SIP_SUBSCRIBE_OBJ     4236	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP.EventSubscribe.i*/
#define RDM_OID_VOICE_PROF_SIP_RESP_MAP_OBJ      4392	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP.ResponseMap.i*/
#define RDM_OID_VOICE_PROF_RTP                   4500	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP*/
#define RDM_OID_VOICE_PROF_RTP_RTCP              4680	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.RTCP*/
#define RDM_OID_VOICE_PROF_RTP_SRTP              4788	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.SRTP*/
#define RDM_OID_VOICE_PROF_RTP_REDUNDANCY        4920	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.Redundancy*/
#define RDM_OID_VOICE_PROF_NUM_PLAN              5148	/*Device.Services.VoiceService.i.VoiceProfile.i.NumberingPlan*/
#define RDM_OID_VOICE_PROF_NUM_PLAN_PREFIX_INFO  5400	/*Device.Services.VoiceService.i.VoiceProfile.i.NumberingPlan.PrefixInfo.i*/
#define RDM_OID_VOICE_PROF_TONE                  5628	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone*/
#define RDM_OID_VOICE_PROF_TONE_EVENT            5736	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Event.i*/
#define RDM_OID_VOICE_PROF_TONE_DESCRIPTION      5820	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Description.i*/
#define RDM_OID_VOICE_PROF_TONE_PATTERN          6024	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Pattern.i*/
#define RDM_OID_VOICE_PROF_FAX_T38               6396	/*Device.Services.VoiceService.i.VoiceProfile.i.FaxT38*/
#define RDM_OID_VOICE_LINE                       6576	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i*/
#define RDM_OID_VOICE_LINE_SIP                   6948	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.SIP*/
#define RDM_OID_VOICE_LINE_SIP_EVENT_SUBS        7224	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.SIP.EventSubscribe.i*/
#define RDM_OID_VOICE_LINE_RINGER                7332	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer*/
#define RDM_OID_VOICE_LINE_RINGER_EVENT          7440	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Event.i*/
#define RDM_OID_VOICE_LINE_RINGER_DESCRIPTION    7524	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Description.i*/
#define RDM_OID_VOICE_LINE_RINGER_PATTERN        7680	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Pattern.i*/
#define RDM_OID_VOICE_LINE_CALLING_FEATURE       7812	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.CallingFeatures*/
#define RDM_OID_VOICE_LINE_PROCESSING            9312	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.VoiceProcessing*/
#define RDM_OID_VOICE_LINE_CODEC                 9468	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Codec*/
#define RDM_OID_VOICE_LINE_CODEC_LIST            9672	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Codec.List.i*/
#define RDM_OID_VOICE_LINE_SESSION               9924	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Session.i*/
#define RDM_OID_VOICE_LINE_STATS                 10080	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Stats*/
#define RDM_OID_VOICE_PHY_INTF                   10860	/*Device.Services.VoiceService.i.PhyInterface.i*/
#define RDM_OID_VOICE_PSTN                       11496	/*Device.Services.VoiceService.i.X_ZYXEL_PSTN.i*/
#define RDM_OID_VOICE_COMMON                     11676	/*Device.Services.VoiceService.i.X_ZYXEL_Common*/
#define RDM_OID_VOICE_PHONE_BOOK                 12048	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook*/
#define RDM_OID_SPEED_DIAL_BOOK                  12084	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.SpeedDialBook*/
#define RDM_OID_SPEED_DIAL_BOOK_LIST             12144	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.SpeedDialBook.List.i*/
#define RDM_OID_CALL_POLICY_BOOK                 12324	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.CallPolicyBook*/
#define RDM_OID_CALL_POLICY_BOOK_LIST            12408	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.CallPolicyBook.List.i*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK 12588	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK_IF_LIST 12648	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook.InterfaceList.i*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK_PORT_LIST 12732	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook.InterfaceList.i.PortList.i*/
#define RDM_OID_VOICE_FXO                        12792	/*Device.Services.VoiceService.i.X_ZYXEL_FXO*/
#define RDM_OID_VOICE_FXO_PORT                   12852	/*Device.Services.VoiceService.i.X_ZYXEL_FXO.Port.i*/
#define RDM_OID_VOICE_DECT                       13128	/*Device.Services.VoiceService.i.X_ZYXEL_DECT*/
#define RDM_OID_VOICE_DECT_B_S                   13188	/*Device.Services.VoiceService.i.X_ZYXEL_DECT.BaseStation*/
#define RDM_OID_VOICE_DECT_H_S                   13680	/*Device.Services.VoiceService.i.X_ZYXEL_DECT.Handset.i*/
#define RDM_OID_VOICE_CALL_STATUS                14004	/*Device.Services.VoiceService.i.X_ZYXEL_CALL_STATUS*/
#define RDM_OID_DEV_INFO                         14232	/*Device.DeviceInfo*/
#define RDM_OID_DEV_INFO_VEND_CONF_FILE          14772	/*Device.DeviceInfo.VendorConfigFile.i*/
#define RDM_OID_DEV_INFO_SUP_DATA_MODEL          14928	/*Device.DeviceInfo.SupportedDataModel.i*/
#define RDM_OID_DEV_INFO_MEM_STAT                15060	/*Device.DeviceInfo.MemoryStatus*/
#define RDM_OID_DEV_INFO_PS_STAT                 15144	/*Device.DeviceInfo.ProcessStatus*/
#define RDM_OID_DEV_INFO_PS_STAT_PS              15228	/*Device.DeviceInfo.ProcessStatus.Process.i*/
#define RDM_OID_TEMP_STAT                        15408	/*Device.DeviceInfo.TemperatureStatus*/
#define RDM_OID_TEMP_STAT_TEMP_SENSOR            15468	/*Device.DeviceInfo.TemperatureStatus.TemperatureSensor.i*/
#define RDM_OID_NETWORK_PROP                     15912	/*Device.DeviceInfo.NetworkProperties.i*/
#define RDM_OID_DEV_INFO_PROCESSOR               15996	/*Device.DeviceInfo.Processor.i*/
#define RDM_OID_DEV_INFO_VENDOR_LOG_FILE         16080	/*Device.DeviceInfo.VendorLogFile.i*/
#define RDM_OID_DEV_INFO_PROXIER_INFO            16212	/*Device.DeviceInfo.ProxierInfo.i*/
#define RDM_OID_DEV_INFO_LOC                     16344	/*Device.DeviceInfo.Location.i*/
#define RDM_OID_MGMT_SRV                         16500	/*Device.ManagementServer*/
#define RDM_OID_MGMT_SRV_MGAB_DEV                18096	/*Device.ManagementServer.ManageableDevice.i*/
#define RDM_OID_MGMT_SRV_AUTO_TRANS_COMPLETE_POL 18276	/*Device.ManagementServer.AutonomousTransferCompletePolicy*/
#define RDM_OID_MGMT_SRV_DL_AVAIL                18408	/*Device.ManagementServer.DownloadAvailability*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_ANNCMNT        18444	/*Device.ManagementServer.DownloadAvailability.Announcement*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_ANNCMNT_GROUP  18552	/*Device.ManagementServer.DownloadAvailability.Announcement.Group.i*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_QUERY          18684	/*Device.ManagementServer.DownloadAvailability.Query*/
#define RDM_OID_MGMT_SRV_DU_STATE_CHANGE_COMPL_POL 18792	/*Device.ManagementServer.DUStateChangeComplPolicy*/
#define RDM_OID_MGMT_SRV_EMBEDED_DEV             18924	/*Device.ManagementServer.EmbeddedDevice.i*/
#define RDM_OID_MGMT_SRV_VIRTUAL_DEV             19176	/*Device.ManagementServer.VirtualDevice.i*/
#define RDM_OID_GATEWAY_INFO                     19332	/*Device.GatewayInfo*/
#define RDM_OID_TIME                             19440	/*Device.Time*/
#define RDM_OID_USR_INTF                         20100	/*Device.UserInterface*/
#define RDM_OID_USR_INTF_REMO_ACESS              20664	/*Device.UserInterface.RemoteAccess*/
#define RDM_OID_USR_INTF_LOCAL_DISP              20796	/*Device.UserInterface.LocalDisplay*/
#define RDM_OID_IFACE_STACK                      21024	/*Device.InterfaceStack.i*/
#define RDM_OID_DSL                              21180	/*Device.DSL*/
#define RDM_OID_DSL_LINE                         21288	/*Device.DSL.Line.i*/
#define RDM_OID_DSL_LINE_ST                      25236	/*Device.DSL.Line.i.Stats*/
#define RDM_OID_DSL_LINE_ST_TOTAL                25584	/*Device.DSL.Line.i.Stats.Total*/
#define RDM_OID_DSL_LINE_ST_SHOWTIME             26076	/*Device.DSL.Line.i.Stats.Showtime*/
#define RDM_OID_DSL_LINE_ST_LAST_SHOWTIME        26568	/*Device.DSL.Line.i.Stats.LastShowtime*/
#define RDM_OID_DSL_LINE_ST_LAST_CUR_DAY         26652	/*Device.DSL.Line.i.Stats.CurrentDay*/
#define RDM_OID_DSL_LINE_ST_LAST_QUAR_HR         27144	/*Device.DSL.Line.i.Stats.QuarterHour*/
#define RDM_OID_DSL_LINE_TEST_PARAMS             27228	/*Device.DSL.Line.i.TestParams*/
#define RDM_OID_DSL_CHANNEL                      27792	/*Device.DSL.Channel.i*/
#define RDM_OID_DSL_CHANNEL_ST                   28284	/*Device.DSL.Channel.i.Stats*/
#define RDM_OID_DSL_CHANNEL_ST_TOTAL             28632	/*Device.DSL.Channel.i.Stats.Total*/
#define RDM_OID_DSL_CHANNEL_ST_SHOWTIME          28812	/*Device.DSL.Channel.i.Stats.Showtime*/
#define RDM_OID_DSL_CHANNEL_ST_LAST_SHOWTIME     28992	/*Device.DSL.Channel.i.Stats.LastShowtime*/
#define RDM_OID_DSL_CHANNEL_ST_CUR_DAY           29172	/*Device.DSL.Channel.i.Stats.CurrentDay*/
#define RDM_OID_DSL_CHANNEL_ST_QUAR_HR           29352	/*Device.DSL.Channel.i.Stats.QuarterHour*/
#define RDM_OID_DSL_BOND_GP                      29532	/*Device.DSL.BondingGroup.i*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL       30048	/*Device.DSL.BondingGroup.i.BondedChannel.i*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL_ETH   30132	/*Device.DSL.BondingGroup.i.BondedChannel.i.Ethernet*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL_ETH_ST 30168	/*Device.DSL.BondingGroup.i.BondedChannel.i.Ethernet.Stats*/
#define RDM_OID_DSL_BOND_GP_ST                   30396	/*Device.DSL.BondingGroup.i.Stats*/
#define RDM_OID_DSL_BOND_GP_ST_TOTAL             30864	/*Device.DSL.BondingGroup.i.Stats.Total*/
#define RDM_OID_DSL_BOND_GP_ST_CURRENT_DAY       31164	/*Device.DSL.BondingGroup.i.Stats.CurrentDay*/
#define RDM_OID_DSL_BOND_GP_ST_QTR_HR            31464	/*Device.DSL.BondingGroup.i.Stats.QuarterHour*/
#define RDM_OID_DSL_BOND_GP_ETH                  31764	/*Device.DSL.BondingGroup.i.Ethernet*/
#define RDM_OID_DSL_BOND_GP_ETH_ST               31800	/*Device.DSL.BondingGroup.i.Ethernet.Stats*/
#define RDM_OID_DSL_DIAG                         32220	/*Device.DSL.Diagnostics*/
#define RDM_OID_DSL_DIAG_ADSL_LINE_TEST          32256	/*Device.DSL.Diagnostics.ADSLLineTest*/
#define RDM_OID_OPT                              33156	/*Device.Optical*/
#define RDM_OID_OPT_INTF                         33216	/*Device.Optical.Interface.i*/
#define RDM_OID_OPT_INTF_ST                      33564	/*Device.Optical.Interface.i.Stats*/
#define RDM_OID_ATM                              33792	/*Device.ATM*/
#define RDM_OID_ATM_LINK                         33852	/*Device.ATM.Link.i*/
#define RDM_OID_ATM_LINK_ST                      34392	/*Device.ATM.Link.i.Stats*/
#define RDM_OID_ATM_LINK_QOS                     34884	/*Device.ATM.Link.i.QoS*/
#define RDM_OID_ATM_DIAG                         35040	/*Device.ATM.Diagnostics*/
#define RDM_OID_ATM_DIAG_F5_LO                   35076	/*Device.ATM.Diagnostics.F5Loopback*/
#define RDM_OID_ATM_DIAG_F4_LO                   35376	/*Device.ATM.Diagnostics.X_ZYXEL_F4Loopback*/
#define RDM_OID_PTM                              35676	/*Device.PTM*/
#define RDM_OID_PTM_LINK                         35736	/*Device.PTM.Link.i*/
#define RDM_OID_PTM_LINK_ST                      36300	/*Device.PTM.Link.i.Stats*/
#define RDM_OID_ETH                              36696	/*Device.Ethernet*/
#define RDM_OID_ETH_RMON_ST                      36828	/*Device.Ethernet.RMONStats.i*/
#define RDM_OID_ETH_IFACE                        37392	/*Device.Ethernet.Interface.i*/
#define RDM_OID_ETH_INTF_ST                      37788	/*Device.Ethernet.Interface.i.Stats*/
#define RDM_OID_ETH_LINK                         38184	/*Device.Ethernet.Link.i*/
#define RDM_OID_ETH_LINK_ST                      38508	/*Device.Ethernet.Link.i.Stats*/
#define RDM_OID_ETH_VLAN_TERM                    38904	/*Device.Ethernet.VLANTermination.i*/
#define RDM_OID_ETH_VLAN_TERM_ST                 39204	/*Device.Ethernet.VLANTermination.i.Stats*/
#define RDM_OID_USB                              39600	/*Device.USB*/
#define RDM_OID_USB_INTF                         39684	/*Device.USB.Interface.i*/
#define RDM_OID_USB_INTF_STAT                    39984	/*Device.USB.Interface.i.Stats*/
#define RDM_OID_USB_PORT                         40380	/*Device.USB.Port.i*/
#define RDM_OID_USB_USBHOSTS                     40608	/*Device.USB.USBHosts*/
#define RDM_OID_USB_USBHOSTS_HOST                40668	/*Device.USB.USBHosts.Host.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV            40896	/*Device.USB.USBHosts.Host.i.Device.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_PAR        41412	/*Device.USB.USBHosts.Host.i.Device.i.X_ZYXEL_Partition.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_CFG        41520	/*Device.USB.USBHosts.Host.i.Device.i.Configuration.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_CFG_INTF   41604	/*Device.USB.USBHosts.Host.i.Device.i.Configuration.i.Interface.i*/
#define RDM_OID_CELLULAR                         41736	/*Device.Cellular*/
#define RDM_OID_CELLULAR_INTERFACE               41844	/*Device.Cellular.Interface.i*/
#define RDM_OID_CELLULAR_IFACE_U_S_I_M           42192	/*Device.Cellular.Interface.i.USIM*/
#define RDM_OID_CELLULAR_ACCESS_POINT            42300	/*Device.Cellular.AccessPoint.i*/
#define RDM_OID_HPNA                             42528	/*Device.HPNA*/
#define RDM_OID_HPNA_INTF                        42588	/*Device.HPNA.Interface.i*/
#define RDM_OID_HPNA_INTF_ST                     43272	/*Device.HPNA.Interface.i.Stats*/
#define RDM_OID_HPNA_INTF_QOS                    43668	/*Device.HPNA.Interface.i.QoS*/
#define RDM_OID_HPNA_INTF_QOS_FLOW_SPEC          43728	/*Device.HPNA.Interface.i.QoS.FlowSpec.i*/
#define RDM_OID_HPNA_INTF_ASSOC_DEV              44100	/*Device.HPNA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_HPNA_DIAG                        44328	/*Device.HPNA.Diagnostics*/
#define RDM_OID_HPNA_DIAG_PHY_THROUGHPUT         44364	/*Device.HPNA.Diagnostics.PHYThroughput*/
#define RDM_OID_HPNA_DIAG_PHY_THROUGHPUT_RESULT  44640	/*Device.HPNA.Diagnostics.PHYThroughput.Result.i*/
#define RDM_OID_HPNA_DIAG_PERF_MONT              44844	/*Device.HPNA.Diagnostics.PerformanceMonitoring*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_NODES     44952	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Nodes*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_NODES_NODE 45060	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Nodes.Node.i*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_CHANNELS  45696	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Channels*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_CHANNELS_CHANNEL 45780	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Channels.Channel.i*/
#define RDM_OID_MOCA                             46080	/*Device.MoCA*/
#define RDM_OID_MOCA_INTF                        46140	/*Device.MoCA.Interface.i*/
#define RDM_OID_MOCA_INTF_ST                     47040	/*Device.MoCA.Interface.i.Stats*/
#define RDM_OID_MOCA_INTF_QOS                    47436	/*Device.MoCA.Interface.i.QoS*/
#define RDM_OID_MOCA_INTF_QOS_FLOW_ST            47544	/*Device.MoCA.Interface.i.QoS.FlowStats.i*/
#define RDM_OID_MOCA_INTF_ASSOC_DEV              47724	/*Device.MoCA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_GHN                              48168	/*Device.Ghn*/
#define RDM_OID_GHN_INTF                         48228	/*Device.Ghn.Interface.i*/
#define RDM_OID_GHN_INTF_ST                      48792	/*Device.Ghn.Interface.i.Stats*/
#define RDM_OID_GHN_INTF_ASSOC_DEV               49188	/*Device.Ghn.Interface.i.AssociatedDevice.i*/
#define RDM_OID_HOME_PLUG                        49344	/*Device.Homeplug*/
#define RDM_OID_HOMEPLUG_INTF                    49404	/*Device.Homeplug.Interface.i*/
#define RDM_OID_HOMEPLUG_INTF_ST                 49824	/*Device.Homeplug.Interface.i.Stats*/
#define RDM_OID_HOMEPLUG_INTF_ASSOC_DEV          50340	/*Device.Homeplug.Interface.i.AssociatedDevice.i*/
#define RDM_OID_UPA                              50544	/*Device.UPA*/
#define RDM_OID_UPA_INTF                         50604	/*Device.UPA.Interface.i*/
#define RDM_OID_UPA_INTF_ST                      51144	/*Device.UPA.Interface.i.Stats*/
#define RDM_OID_UPA_INTF_ASSOC_DEV               51540	/*Device.UPA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_UPA_INTF_ACTIVE_NOTCH            51840	/*Device.UPA.Interface.i.ActiveNotch.i*/
#define RDM_OID_UPA_INTF_BRIDGE_FOR              51996	/*Device.UPA.Interface.i.BridgeFor.i*/
#define RDM_OID_UPA_DIAG                         52104	/*Device.UPA.Diagnostics*/
#define RDM_OID_UPA_DIAG_INTF_MEASUREMENT        52140	/*Device.UPA.Diagnostics.InterfaceMeasurement*/
#define RDM_OID_WIFI                             52320	/*Device.WiFi*/
#define RDM_OID_WIFI_ONE_SSID                    52476	/*Device.WiFi.X_ZYXEL_OneSSID*/
#define RDM_OID_WIFI_RADIO                       52536	/*Device.WiFi.Radio.i*/
#define RDM_OID_WIFI_RADIO_ST                    54108	/*Device.WiFi.Radio.i.Stats*/
#define RDM_OID_WIFI_SSID                        54360	/*Device.WiFi.SSID.i*/
#define RDM_OID_WIFI_SSID_STAT                   54900	/*Device.WiFi.SSID.i.Stats*/
#define RDM_OID_WIFI_ACCESS_POINT                55296	/*Device.WiFi.AccessPoint.i*/
#define RDM_OID_WIFI_ACCESS_POINT_SEC            55668	/*Device.WiFi.AccessPoint.i.Security*/
#define RDM_OID_WIFI_ACCESS_POINT_ACCOUNTING     56688	/*Device.WiFi.AccessPoint.i.Accounting*/
#define RDM_OID_WIFI_ACCESS_POINT_WPS            56916	/*Device.WiFi.AccessPoint.i.WPS*/
#define RDM_OID_WIFI_ACCESS_POINT_ASSOC_DEV      57312	/*Device.WiFi.AccessPoint.i.AssociatedDevice.i*/
#define RDM_OID_WIFI_ACCESS_POINT_ASSOC_DEV_ST   57588	/*Device.WiFi.AccessPoint.i.AssociatedDevice.i.Stats*/
#define RDM_OID_WIFI_STA_FILTER                  57840	/*Device.WiFi.AccessPoint.i.StationFilter*/
#define RDM_OID_WIFI_END_POINT                   57924	/*Device.WiFi.EndPoint.i*/
#define RDM_OID_WIFI_END_POINT_ST                58104	/*Device.WiFi.EndPoint.i.Stats*/
#define RDM_OID_WIFI_END_POINT_SEC               58236	/*Device.WiFi.EndPoint.i.Security*/
#define RDM_OID_WIFI_END_POINT_PROFILE           58296	/*Device.WiFi.EndPoint.i.Profile.i*/
#define RDM_OID_WIFI_END_POINT_PROFILE_SEC       58476	/*Device.WiFi.EndPoint.i.Profile.i.Security*/
#define RDM_OID_WPS                              58608	/*Device.WiFi.EndPoint.i.WPS*/
#define RDM_OID_WIFI_DIAGNOSTIC                  58716	/*Device.WiFi.NeighboringWiFiDiagnostic*/
#define RDM_OID_WIFI_DIAGNOSTIC_RESULTS          58824	/*Device.WiFi.NeighboringWiFiDiagnostic.Result.i*/
#define RDM_OID_WIFI_AP_STEERING                 59268	/*Device.WiFi.X_ZYXEL_ApSteering*/
#define RDM_OID_WLAN_SCHEDULER                   59712	/*Device.WiFi.X_ZYXEL_WLAN_Scheduler.i*/
#define RDM_OID_BRIDGING                         60036	/*Device.Bridging*/
#define RDM_OID_BRIDGING_BR                      60312	/*Device.Bridging.Bridge.i*/
#define RDM_OID_BRIDGING_BR_PORT                 60612	/*Device.Bridging.Bridge.i.Port.i*/
#define RDM_OID_BRIDGING_BR_PORT_ST              61080	/*Device.Bridging.Bridge.i.Port.i.Stats*/
#define RDM_OID_BRIDGING_BR_VLAN                 61476	/*Device.Bridging.Bridge.i.VLAN.i*/
#define RDM_OID_BRIDGING_BR_VLANPORT             61608	/*Device.Bridging.Bridge.i.VLANPort.i*/
#define RDM_OID_BRIDGING_FILTER                  61764	/*Device.Bridging.Filter.i*/
#define RDM_OID_PPP                              62592	/*Device.PPP*/
#define RDM_OID_PPP_IFACE                        62676	/*Device.PPP.Interface.i*/
#define RDM_OID_PPP_IFACE_PPPOA                  63624	/*Device.PPP.Interface.i.PPPoA*/
#define RDM_OID_PPP_IFACE_PPPOE                  63660	/*Device.PPP.Interface.i.PPPoE*/
#define RDM_OID_PPP_IFACE_IPCP                   63792	/*Device.PPP.Interface.i.IPCP*/
#define RDM_OID_PPP_INTF_IPV6CP                  63948	/*Device.PPP.Interface.i.IPV6CP*/
#define RDM_OID_PPP_IFACE_STAT                   64032	/*Device.PPP.Interface.i.Stats*/
#define RDM_OID_IP                               64428	/*Device.IP*/
#define RDM_OID_IP_IFACE                         64680	/*Device.IP.Interface.i*/
#define RDM_OID_IP_IFACE_V4_ADDR                 66108	/*Device.IP.Interface.i.IPv4Address.i*/
#define RDM_OID_IP_IFACE_V6_ADDR                 66360	/*Device.IP.Interface.i.IPv6Address.i*/
#define RDM_OID_IP_IFACE_V6_PREFIX               66660	/*Device.IP.Interface.i.IPv6Prefix.i*/
#define RDM_OID_IP_IFACE_STAT                    67080	/*Device.IP.Interface.i.Stats*/
#define RDM_OID_IP_ACTIVE_PORT                   67476	/*Device.IP.ActivePort.i*/
#define RDM_OID_IP_DIAG                          67632	/*Device.IP.Diagnostics*/
#define RDM_OID_IP_DIAG_IPPING                   67668	/*Device.IP.Diagnostics.IPPing*/
#define RDM_OID_IP_DIAG_TRACE_RT                 68112	/*Device.IP.Diagnostics.TraceRoute*/
#define RDM_OID_IP_DIAG_TRACERT_RT_HOPS          68436	/*Device.IP.Diagnostics.TraceRoute.RouteHops.i*/
#define RDM_OID_IP_DIAG_DL_DIAG                  68568	/*Device.IP.Diagnostics.DownloadDiagnostics*/
#define RDM_OID_IP_DIAG_UL_DIAG                  69036	/*Device.IP.Diagnostics.UploadDiagnostics*/
#define RDM_OID_IP_DIAG_UDP_ECHO_CFG             69456	/*Device.IP.Diagnostics.UDPEchoConfig*/
#define RDM_OID_IP_DIAG_UDP_ECHO_DIAG            69780	/*Device.IP.Diagnostics.UDPEchoDiagnostics*/
#define RDM_OID_IP_DIAG_UDP_ECHO_PAK_RST         70296	/*Device.IP.Diagnostics.UDPEchoDiagnostics.IndividualPacketResult.i*/
#define RDM_OID_IP_DIAG_SVR_SELECT_DIAG          70524	/*Device.IP.Diagnostics.ServerSelectionDiagnostics*/
#define RDM_OID_IPSEC                            70848	/*Device.IPSec*/
#define RDM_OID_IPSEC_STAT                       71220	/*Device.IPSec.Stats*/
#define RDM_OID_IPSEC_FILTER                     71544	/*Device.IPSec.Filter.i*/
#define RDM_OID_IPSEC_PROFILE                    72108	/*Device.IPSec.Profile.i*/
#define RDM_OID_IPSEC_PROFILE_SENT_CP_ATTR       72744	/*Device.IPSec.Profile.i.SentCPAttr.i*/
#define RDM_OID_IPSEC_TUNNEL                     72876	/*Device.IPSec.Tunnel.i*/
#define RDM_OID_IPSEC_TUNNEL_STAT                73008	/*Device.IPSec.Tunnel.i.Stats*/
#define RDM_OID_IPSEC_IKEV2SA                    73164	/*Device.IPSec.IKEv2SA.i*/
#define RDM_OID_IPSEC_IKEV2SA_STAT               73512	/*Device.IPSec.IKEv2SA.i.Stats*/
#define RDM_OID_IPSEC_IKEV2SA_RECEIVED_CP_ATTR   73740	/*Device.IPSec.IKEv2SA.i.ReceivedCPAttr.i*/
#define RDM_OID_IPSEC_IKEV2SA_CHILD_SA           73824	/*Device.IPSec.IKEv2SA.i.ChildSA.i*/
#define RDM_OID_IPSEC_IKEV2SA_CHILD_SA_STAT      73980	/*Device.IPSec.IKEv2SA.i.ChildSA.i.Stats*/
#define RDM_OID_GRE                              74256	/*Device.GRE*/
#define RDM_OID_GRE_TUNNEL                       74340	/*Device.GRE.Tunnel.i*/
#define RDM_OID_GRE_TUNNEL_STAT                  74640	/*Device.GRE.Tunnel.i.Stats*/
#define RDM_OID_GRE_TUNNEL_IFACE                 74868	/*Device.GRE.Tunnel.i.Interface.i*/
#define RDM_OID_GRE_TUNNEL_IFACE_STAT            75168	/*Device.GRE.Tunnel.i.Interface.i.Stats*/
#define RDM_OID_GRE_FILTER                       75396	/*Device.GRE.Filter.i*/
#define RDM_OID_CAPT_PORTAL                      75648	/*Device.CaptivePortal*/
#define RDM_OID_ROUTING                          75780	/*Device.Routing*/
#define RDM_OID_ROUTING_ROUTER                   75840	/*Device.Routing.Router.i*/
#define RDM_OID_ROUTING_ROUTER_V4_FWD            76068	/*Device.Routing.Router.i.IPv4Forwarding.i*/
#define RDM_OID_ROUTING_ROUTER_V6_FWD            76560	/*Device.Routing.Router.i.IPv6Forwarding.i*/
#define RDM_OID_ROUTING_RIP                      76836	/*Device.Routing.RIP*/
#define RDM_OID_ROUTING_RIP_INTF_SET             76944	/*Device.Routing.RIP.InterfaceSetting.i*/
#define RDM_OID_ROUTING_RT_INFO                  77196	/*Device.Routing.RouteInformation*/
#define RDM_OID_ROUTING_RT_INFO_INTF_SET         77280	/*Device.Routing.RouteInformation.InterfaceSetting.i*/
#define RDM_OID_NEIGHBOR_DISCOVERY               77532	/*Device.NeighborDiscovery*/
#define RDM_OID_NEIGHBOR_DISCOVERY_INTF_SET      77616	/*Device.NeighborDiscovery.InterfaceSetting.i*/
#define RDM_OID_RT_ADV                           77868	/*Device.RouterAdvertisement*/
#define RDM_OID_RT_ADV_INTF_SET                  77952	/*Device.RouterAdvertisement.InterfaceSetting.i*/
#define RDM_OID_RT_ADV_INTF_SET_OPT              78540	/*Device.RouterAdvertisement.InterfaceSetting.i.Option.i*/
#define RDM_OID_IPV6RD                           78672	/*Device.IPv6rd*/
#define RDM_OID_IPV6RD_INTF                      78756	/*Device.IPv6rd.InterfaceSetting.i*/
#define RDM_OID_DS_LITE                          79056	/*Device.DSLite*/
#define RDM_OID_DS_LITE_INTF_SET                 79140	/*Device.DSLite.InterfaceSetting.i*/
#define RDM_OID_QOS                              79488	/*Device.QoS*/
#define RDM_OID_QOS_CLS                          80100	/*Device.QoS.Classification.i*/
#define RDM_OID_QOS_APP                          82224	/*Device.QoS.App.i*/
#define RDM_OID_QOS_FLOW                         82500	/*Device.QoS.Flow.i*/
#define RDM_OID_QOS_POLICER                      82824	/*Device.QoS.Policer.i*/
#define RDM_OID_QOS_QUE                          83388	/*Device.QoS.Queue.i*/
#define RDM_OID_QOS_QUE_STAT                     83928	/*Device.QoS.QueueStats.i*/
#define RDM_OID_QOS_SHAPER                       84228	/*Device.QoS.Shaper.i*/
#define RDM_OID_LAN_CONF_SEC                     84408	/*Device.LANConfigSecurity*/
#define RDM_OID_HOSTS                            84468	/*Device.Hosts*/
#define RDM_OID_HOSTS_HOST                       84528	/*Device.Hosts.Host.i*/
#define RDM_OID_HOSTS_HOST_V4_ADDR               85284	/*Device.Hosts.Host.i.IPv4Address.i*/
#define RDM_OID_HOSTS_HOST_V6_ADDR               85344	/*Device.Hosts.Host.i.IPv6Address.i*/
#define RDM_OID_ZY_HOSTS_HOST_EXT                85404	/*Device.Hosts.Host.i.X_ZYXEL_EXT*/
#define RDM_OID_DNS                              85704	/*Device.DNS*/
#define RDM_OID_DNS_CLIENT                       85812	/*Device.DNS.Client*/
#define RDM_OID_DNS_CLIENT_SRV                   85920	/*Device.DNS.Client.Server.i*/
#define RDM_OID_DNS_RELAY                        86196	/*Device.DNS.Relay*/
#define RDM_OID_DNS_RELAY_FWD                    86304	/*Device.DNS.Relay.Forwarding.i*/
#define RDM_OID_DNS_DIAG                         86484	/*Device.DNS.Diagnostics*/
#define RDM_OID_DNS_DIAG_NS_LOOKUP_DIAG          86520	/*Device.DNS.Diagnostics.NSLookupDiagnostics*/
#define RDM_OID_DNS_DIAG_NS_LOOKUP_DIAG_RESULT   86772	/*Device.DNS.Diagnostics.NSLookupDiagnostics.Result.i*/
#define RDM_OID_NAT                              86952	/*Device.NAT*/
#define RDM_OID_NAT_INTF_SETTING                 87180	/*Device.NAT.InterfaceSetting.i*/
#define RDM_OID_NAT_PORT_MAPPING                 87336	/*Device.NAT.PortMapping.i*/
#define RDM_OID_NAT_PORT_TRIGGERING              87852	/*Device.NAT.X_ZYXEL_PortTriggering.i*/
#define RDM_OID_NAT_ADDR_MAPPING                 88152	/*Device.NAT.X_ZYXEL_AddrMapping.i*/
#define RDM_OID_NAT_SESSION_CTL                  88452	/*Device.NAT.X_ZYXEL_SessionControl*/
#define RDM_OID_DHCPV4                           88536	/*Device.DHCPv4*/
#define RDM_OID_DHCPV4_CLIENT                    88596	/*Device.DHCPv4.Client.i*/
#define RDM_OID_DHCPV4_SENT_OPT                  89064	/*Device.DHCPv4.Client.i.SentOption.i*/
#define RDM_OID_DHCPV4_REQ_OPT                   89196	/*Device.DHCPv4.Client.i.ReqOption.i*/
#define RDM_OID_DHCPV4_SRV                       89352	/*Device.DHCPv4.Server*/
#define RDM_OID_DHCPV4_SRV_POOL                  89436	/*Device.DHCPv4.Server.Pool.i*/
#define RDM_OID_DHCPV4_SRV_POOL_STATIC_ADDR      90288	/*Device.DHCPv4.Server.Pool.i.StaticAddress.i*/
#define RDM_OID_DHCPV4_SRV_POOL_OPT              90420	/*Device.DHCPv4.Server.Pool.i.Option.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT           90552	/*Device.DHCPv4.Server.Pool.i.Client.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT_V4_ADDR   90708	/*Device.DHCPv4.Server.Pool.i.Client.i.IPv4Address.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT_OPT       90792	/*Device.DHCPv4.Server.Pool.i.Client.i.Option.i*/
#define RDM_OID_DHCPV4_SRV_SUBNET                90876	/*Device.DHCPv4.Server.X_ZYXEL_Subnet.i*/
#define RDM_OID_DHCPV4_RELAY                     91056	/*Device.DHCPv4.Relay*/
#define RDM_OID_DHCPV4_RELAY_FWD                 91164	/*Device.DHCPv4.Relay.Forwarding.i*/
#define RDM_OID_DHCPV6                           91608	/*Device.DHCPv6*/
#define RDM_OID_DHCPV6_CLIENT                    91668	/*Device.DHCPv6.Client.i*/
#define RDM_OID_DHCPV6_CLIENT_SRV                92112	/*Device.DHCPv6.Client.i.Server.i*/
#define RDM_OID_DHCPV6_CLIENT_SENT_OPT           92220	/*Device.DHCPv6.Client.i.SentOption.i*/
#define RDM_OID_DHCPV6_CLIENT_RECEIVED_OPT       92352	/*Device.DHCPv6.Client.i.ReceivedOption.i*/
#define RDM_OID_DHCPV6_SRV                       92460	/*Device.DHCPv6.Server*/
#define RDM_OID_DHCPV6_SRV_POOL                  92544	/*Device.DHCPv6.Server.Pool.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT           93276	/*Device.DHCPv6.Server.Pool.i.Client.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_V6_ADDR   93456	/*Device.DHCPv6.Server.Pool.i.Client.i.IPv6Address.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_V6_PREFIX 93564	/*Device.DHCPv6.Server.Pool.i.Client.i.IPv6Prefix.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_OPT       93672	/*Device.DHCPv6.Server.Pool.i.Client.i.Option.i*/
#define RDM_OID_DHCPV6_SRV_POOL_OPT              93756	/*Device.DHCPv6.Server.Pool.i.Option.i*/
#define RDM_OID_IEEE8021X                        93912	/*Device.IEEE8021x*/
#define RDM_OID_IEEE8021X_SUPPLICANT             93972	/*Device.IEEE8021x.Supplicant.i*/
#define RDM_OID_IEEE8021X_SUPPLICANT_STAT        94440	/*Device.IEEE8021x.Supplicant.i.Stats*/
#define RDM_OID_IEEE8021X_SUPPLICANT_EAPMD5      94740	/*Device.IEEE8021x.Supplicant.i.EAPMD5*/
#define RDM_OID_IEEE8021X_SUPPLICANT_EAPTLS      94824	/*Device.IEEE8021x.Supplicant.i.EAPTLS*/
#define RDM_OID_USRS                             94908	/*Device.Users*/
#define RDM_OID_USRS_USR                         94968	/*Device.Users.User.i*/
#define RDM_OID_SMART_CARD_READERS               95148	/*Device.SmartCardReaders*/
#define RDM_OID_SMART_CARD_READERS_SCR           95208	/*Device.SmartCardReaders.SmartCardReader.i*/
#define RDM_OID_SMART_CARD_READERS_SCR_SC        95436	/*Device.SmartCardReaders.SmartCardReader.i.SmartCard*/
#define RDM_OID_UPNP                             95592	/*Device.UPnP*/
#define RDM_OID_UPNP_DEV                         95628	/*Device.UPnP.Device*/
#define RDM_OID_UPNP_DEV_CAPB                    95952	/*Device.UPnP.Device.Capabilities*/
#define RDM_OID_UPNP_DISC                        96276	/*Device.UPnP.Discovery*/
#define RDM_OID_UPNP_DISC_ROOT_DEV               96384	/*Device.UPnP.Discovery.RootDevice.i*/
#define RDM_OID_UPNP_DISC_DEV                    96588	/*Device.UPnP.Discovery.Device.i*/
#define RDM_OID_UPNP_DISC_SERVICE                96792	/*Device.UPnP.Discovery.Service.i*/
#define RDM_OID_DLNA                             96972	/*Device.DLNA*/
#define RDM_OID_DLNA_CAPB                        97152	/*Device.DLNA.Capabilities*/
#define RDM_OID_SELF_TEST_DIAG                   97380	/*Device.SelfTestDiagnostics*/
#define RDM_OID_FIREWALL                         97464	/*Device.Firewall*/
#define RDM_OID_FIREWALL_LEVEL                   97788	/*Device.Firewall.Level.i*/
#define RDM_OID_FIREWALL_CHAIN                   98040	/*Device.Firewall.Chain.i*/
#define RDM_OID_FIREWALL_CHAIN_RULE              98196	/*Device.Firewall.Chain.i.Rule.i*/
#define RDM_OID_PERD_STATISTICS                  99240	/*Device.PeriodicStatistics*/
#define RDM_OID_PERD_STATISTICS_SAMPLE_SET       99348	/*Device.PeriodicStatistics.SampleSet.i*/
#define RDM_OID_PERD_STATISTICS_SAMPLE_SET_PARAM 99696	/*Device.PeriodicStatistics.SampleSet.i.Parameter.i*/
#define RDM_OID_SW_MODULE                        99996	/*Device.SoftwareModules*/
#define RDM_OID_SW_MODULE_EXEC_ENV               100104	/*Device.SoftwareModules.ExecEnv.i*/
#define RDM_OID_SW_MODULE_DEPLOYMENT_UNIT        100596	/*Device.SoftwareModules.DeploymentUnit.i*/
#define RDM_OID_SW_MODULE_EXEC_UNIT              100968	/*Device.SoftwareModules.ExecutionUnit*/
#define RDM_OID_SW_MODULE_EXEC_UNIT_EXT          101508	/*Device.SoftwareModules.ExecutionUnit.Extensions*/
#define RDM_OID_FAULT_MGMT                       101544	/*Device.FaultMgmt*/
#define RDM_OID_FAULT_MGMT_SUPT_ALARM            101724	/*Device.FaultMgmt.SupportedAlarm.i*/
#define RDM_OID_FAULT_MGMT_CURRENT_ALARM         101880	/*Device.FaultMgmt.CurrentAlarm.i*/
#define RDM_OID_FAULT_MGMT_HISTORY_EVENT         102156	/*Device.FaultMgmt.HistoryEvent.i*/
#define RDM_OID_FAULT_MGMT_EXPEDITED_EVENT       102432	/*Device.FaultMgmt.ExpeditedEvent.i*/
#define RDM_OID_FAULT_MGMT_QUED_EVENT            102708	/*Device.FaultMgmt.QueuedEvent.i*/
#define RDM_OID_DEV_SEC                          102984	/*Device.Security*/
#define RDM_OID_DEV_SEC_CERT                     103044	/*Device.Security.Certificate.i*/
#define RDM_OID_FAP                              103512	/*Device.FAP*/
#define RDM_OID_FAP_GPS                          103548	/*Device.FAP.GPS*/
#define RDM_OID_FAP_GPS_CONTS_GPS_STATUS         103920	/*Device.FAP.GPS.ContinuousGPSStatus*/
#define RDM_OID_FAP_GPS_AGPS_SRV_CONF            104292	/*Device.FAP.GPS.AGPSServerConfig*/
#define RDM_OID_FAP_PERF_MGMT                    104520	/*Device.FAP.PerfMgmt*/
#define RDM_OID_FAP_PERF_MGMT_CONF               104580	/*Device.FAP.PerfMgmt.Config.i*/
#define RDM_OID_FAP_APP_PLATF                    104784	/*Device.FAP.ApplicationPlatform*/
#define RDM_OID_FAP_APP_PLATF_CAPB               104940	/*Device.FAP.ApplicationPlatform.Capabilities*/
#define RDM_OID_FAP_APP_PLATF_CTRL               105288	/*Device.FAP.ApplicationPlatform.Control*/
#define RDM_OID_FAP_APP_PLATF_CTRL_FEMTO_AWARE   105372	/*Device.FAP.ApplicationPlatform.Control.FemtoAwareness*/
#define RDM_OID_FAP_APP_PLATF_CTRL_SMS           105600	/*Device.FAP.ApplicationPlatform.Control.SMS*/
#define RDM_OID_FAP_APP_PLATF_CTRL_MMS           105804	/*Device.FAP.ApplicationPlatform.Control.MMS*/
#define RDM_OID_FAP_APP_PLATF_CTRL_TERM_LOC      106008	/*Device.FAP.ApplicationPlatform.Control.TerminalLocation*/
#define RDM_OID_FAP_APP_PLATF_MONT               106236	/*Device.FAP.ApplicationPlatform.Monitoring*/
#define RDM_OID_FAP_APP_PLATF_MONT_FEMTO_AWARE   106368	/*Device.FAP.ApplicationPlatform.Monitoring.FemtoAwareness*/
#define RDM_OID_FAP_APP_PLATF_MONT_SMS           106548	/*Device.FAP.ApplicationPlatform.Monitoring.SMS*/
#define RDM_OID_FAP_APP_PLATF_MONT_MMS           106728	/*Device.FAP.ApplicationPlatform.Monitoring.MMS*/
#define RDM_OID_FAP_APP_PLATF_MONT_TERM_LOC      106908	/*Device.FAP.ApplicationPlatform.Monitoring.TerminalLocation*/
#define RDM_OID_BULK_DATA                        107088	/*Device.BulkData*/
#define RDM_OID_BULK_DATA_PROF                   107316	/*Device.BulkData.Profile.i*/
#define RDM_OID_BULK_DATA_PROF_PARAM             107688	/*Device.BulkData.Profile.i.Parameter.i*/
#define RDM_OID_ROM_CONVERT                      107748	/*Device.X_ZYXEL_RomConvert.i*/
#define RDM_OID_SCHEDULE                         107808	/*Device.X_ZYXEL_Schedule.i*/
#define RDM_OID_EMAIL_NOTIFY                     108084	/*Device.X_ZYXEL_EmailNotification*/
#define RDM_OID_MAIL_SERVICE                     108120	/*Device.X_ZYXEL_EmailNotification.EmailService.i*/
#define RDM_OID_MAIL_EVENT_CFG                   108348	/*Device.X_ZYXEL_EmailNotification.EmailEventConfig.i*/
#define RDM_OID_PAREN_CTL                        108528	/*Device.X_ZYXEL_ParentalControl*/
#define RDM_OID_PAREN_CTL_PROF                   108588	/*Device.X_ZYXEL_ParentalControl.Profile.i*/
#define RDM_OID_IEEE8021AG                       108840	/*Device.X_ZYXEL_8021ag*/
#define RDM_OID_IEEE8023AH                       109332	/*Device.X_ZYXEL_8023ah*/
#define RDM_OID_ZY_EXT                           109584	/*Device.X_ZYXEL_EXT*/
#define RDM_OID_DNS_RT_ENTRY                     109620	/*Device.X_ZYXEL_EXT.DNSRouteEntry.i*/
#define RDM_OID_DNS_ENTRY                        109824	/*Device.X_ZYXEL_EXT.DNSEntry.i*/
#define RDM_OID_D_DNS                            109908	/*Device.X_ZYXEL_EXT.DynamicDNS*/
#define RDM_OID_AUTO_PROV                        110328	/*Device.X_ZYXEL_EXT.AutoProvision*/
#define RDM_OID_SPEED_TEST                       110556	/*Device.X_ZYXEL_EXT.SpeedTestInfo*/
#define RDM_OID_WIFI_QSTEER                      110664	/*Device.X_ZYXEL_EXT.Qsteer*/
#define RDM_OID_ZY_IGMP                          110796	/*Device.X_ZYXEL_IGMP*/
#define RDM_OID_ZY_SNMP                          111240	/*Device.X_ZYXEL_SNMP*/
#define RDM_OID_TRAP_ADDR                        111396	/*Device.X_ZYXEL_SNMP.TrapAddr.i*/
#define RDM_OID_ZY_MLD                           111504	/*Device.X_ZYXEL_MLD*/
#define RDM_OID_ZY_LOG_CFG                       111924	/*Device.X_ZYXEL_LoginCfg*/
#define RDM_OID_ZY_LOG_CFG_GP                    112032	/*Device.X_ZYXEL_LoginCfg.LogGp.i*/
#define RDM_OID_ZY_LOG_CFG_GP_ACCOUNT            112164	/*Device.X_ZYXEL_LoginCfg.LogGp.i.Account.i*/
#define RDM_OID_ZY_MAC_FILTER                    112776	/*Device.X_ZYXEL_MacFilter*/
#define RDM_OID_ZY_MAC_FILTER_WHITE_LIST         112884	/*Device.X_ZYXEL_MacFilter.WhiteList.i*/
#define RDM_OID_WLAN_SCHEDULER_ACCESS            112992	/*Device.X_ZYXEL_WlanSchedulerAccess*/
#define RDM_OID_VC_AUTO_HUNT                     113052	/*Device.X_ZYXEL_VcAutoHunt*/
#define RDM_OID_VC_HUNT_INFO                     113208	/*Device.X_ZYXEL_VcAutoHunt.VcHuntInfo.i*/
#define RDM_OID_VC_HUNT_RULE                     113292	/*Device.X_ZYXEL_VcAutoHunt.VcHuntInfo.i.VcHuntRule.i*/
#define RDM_OID_VLAN_AUTO_HUNT                   113376	/*Device.X_ZYXEL_VlanAutoHunt*/
#define RDM_OID_VLAN_HUNT_INFO                   113508	/*Device.X_ZYXEL_VlanAutoHunt.VlanHuntInfo.i*/
#define RDM_OID_VLAN_HUNT_RULE                   113592	/*Device.X_ZYXEL_VlanAutoHunt.VlanHuntInfo.i.VlanHuntRule.i*/
#define RDM_OID_LANG                             113676	/*Device.X_ZYXEL_Language*/
#define RDM_OID_REMO_MGMT                        113736	/*Device.X_ZYXEL_RemoteManagement*/
#define RDM_OID_REMO_SRV                         113820	/*Device.X_ZYXEL_RemoteManagement.Service.i*/
#define RDM_OID_REMO_SRV_TRUST_DOMAIN            114096	/*Device.X_ZYXEL_RemoteManagement.Service.i.TrustDomain.i*/
#define RDM_OID_SP_REMO_SRV                      114204	/*Device.X_ZYXEL_RemoteManagement.SPService.i*/
#define RDM_OID_SP_REMO_SRV_TRUST_DOMAIN         114480	/*Device.X_ZYXEL_RemoteManagement.SPService.i.TrustDomain.i*/
#define RDM_OID_REMO_MGMT_TRUST_DOMAIN           114612	/*Device.X_ZYXEL_RemoteManagement.TrustDomain.i*/
#define RDM_OID_SP_TRUST_DOMAIN                  114720	/*Device.X_ZYXEL_RemoteManagement.SPTrustDomain.i*/
#define RDM_OID_NETWORK_SRV                      114852	/*Device.X_ZYXEL_NetworkService*/
#define RDM_OID_NETWORK_SRV_GP                   114912	/*Device.X_ZYXEL_NetworkService.Service.i*/
#define RDM_OID_SYSTEM_INFO                      115164	/*Device.X_ZYXEL_System_Info*/
#define RDM_OID_LOG_SETTING                      115368	/*Device.X_ZYXEL_Log_Setting*/
#define RDM_OID_LOG_CLASSIFY                     115548	/*Device.X_ZYXEL_Log_Setting.LogClassify.i*/
#define RDM_OID_LOG_CATEGORY                     115656	/*Device.X_ZYXEL_Log_Setting.LogClassify.i.Category.i*/
#define RDM_OID_CHANGE_ICON_NAME                 115812	/*Device.X_ZYXEL_Change_Icon_Name.i*/
#define RDM_OID_PORT_MIRROR                      115920	/*Device.X_ZYXEL_PortMirroring.i*/
#define RDM_OID_VLAN_GROUP                       116052	/*Device.X_ZYXEL_VlanGroup.i*/
#define RDM_OID_S_T_B_VENDOR_I_D                 116232	/*Device.X_ZYXEL_STB_VENDOR_ID*/
#define RDM_OID_T_F_T_P_SRV_NAME                 116388	/*Device.X_ZYXEL_TFTP_SERVER_NAME*/
#define RDM_OID_TR064                            116448	/*Device.X_ZYXEL_TR064*/
#define RDM_OID_ZY_W_W_A_N_BACKUP                116508	/*Device.X_ZYXEL_WWAN_BACKUP*/
#define RDM_OID_ZY_W_W_A_N_PING_CHECK            116904	/*Device.X_ZYXEL_WWAN_BACKUP.PingCheck*/
#define RDM_OID_ZY_W_W_A_N_BUDGET_CONTROL        117060	/*Device.X_ZYXEL_WWAN_BACKUP.BudgetControl*/
#define RDM_OID_ZY_W_W_A_N_STAT                  117744	/*Device.X_ZYXEL_WWAN_BACKUP.Stats*/
#define RDM_OID_ZY_SAMBA                         117972	/*Device.X_ZYXEL_SAMBA*/
#define RDM_OID_ZY_SAMBA_DIR                     118056	/*Device.X_ZYXEL_SAMBA.Directory.i*/
#define RDM_OID_GUI_CUSTOMIZATION                118308	/*Device.X_ZYXEL_GUI_CUSTOMIZATION*/
#define RDM_OID_FEATURE_FLAG                     118560	/*Device.X_ZYXEL_FEATRUE_FLAG*/
#define RDM_OID_ZY_OPTION125                     118716	/*Device.X_ZYXEL_Option125VendorSpecific*/
#define RDM_OID_ZY_VENDOR_SPECIFIC               118776	/*Device.X_ZYXEL_Option125VendorSpecific.VendorSpecific.i*/
#define RDM_OID_ZY_IPP_CFG                       118908	/*Device.X_ZYXEL_Ipp_Cfg*/
#define RDM_OID_GPON                             119040	/*Device.X_ZYXEL_GPON*/
#define RDM_OID_ONU                              119076	/*Device.X_ZYXEL_GPON.ONU*/
#define RDM_OID_ANI                              119784	/*Device.X_ZYXEL_GPON.ANI*/
#define RDM_OID_OLT                              120252	/*Device.X_ZYXEL_GPON.OLT*/
#define RDM_OID_CAPABILITY                       120384	/*Device.X_ZYXEL_GPON.Capability*/
#define RDM_OID_LOIDAUTH                         120492	/*Device.X_ZYXEL_GPON.LOIDAuth*/
#define RDM_OID_SOFTIMAGE                        120600	/*Device.X_ZYXEL_GPON.SoftImage.i*/
#define RDM_OID_PM                               120732	/*Device.X_ZYXEL_GPON.PM*/
#define RDM_OID_COMMON                           120888	/*Device.X_ZYXEL_GPON.Common*/
#define RDM_OID_XPON                             120972	/*Device.X_ZYXEL_GPON.Xpon*/
#define RDM_OID_LINKCFG                          121128	/*Device.X_ZYXEL_GPON.LinkCfg*/
#define RDM_OID_IPHOST                           121212	/*Device.X_ZYXEL_GPON.IPHost*/
#define RDM_OID_OMCI_CFG                         121296	/*Device.X_ZYXEL_GPON.OmciConfig*/
#define RDM_OID_OMCI                             121332	/*Device.X_ZYXEL_GPON.OmciConfig.Omci*/
#define RDM_OID_GEMPORT                          121536	/*Device.X_ZYXEL_GPON.OmciConfig.GEMPort*/
#define RDM_OID_TCONT                            121692	/*Device.X_ZYXEL_GPON.OmciConfig.TCONT*/
#define RDM_OID_TRTCM                            121776	/*Device.X_ZYXEL_GPON.OmciConfig.Trtcm*/
#define RDM_OID_QOSCFG                           121932	/*Device.X_ZYXEL_GPON.OmciConfig.QosCfg*/
#define RDM_OID_QOS_VALUE                        122112	/*Device.X_ZYXEL_GPON.OmciConfig.QosCfg.QOSValue.i*/
#define RDM_OID_CNGSTCFG                         122172	/*Device.X_ZYXEL_GPON.OmciConfig.CngstCfg*/
#define RDM_OID_CONGEST_THRED_VALUE              122400	/*Device.X_ZYXEL_GPON.OmciConfig.CngstCfg.CongestThredValue.i*/
#define RDM_OID_TRTCMCFG                         122460	/*Device.X_ZYXEL_GPON.OmciConfig.TrtcmCfg*/
#define RDM_OID_TRTCM_VALUE                      122592	/*Device.X_ZYXEL_GPON.OmciConfig.TrtcmCfg.TrtcmValue.i*/
#define RDM_OID_QUEUE                            122652	/*Device.X_ZYXEL_GPON.OmciConfig.Queue*/
#define RDM_OID_ONT_GENERIC                      122712	/*Device.X_ZYXEL_GPON.OntGeneric*/
#define RDM_OID_ZY_ONE_CONNECT                   122772	/*Device.X_ZYXEL_OneConnect*/
#define RDM_OID_ONE_CONNECT_INTERNET_ACCESS_MASTER_SWITCH 122856	/*Device.X_ZYXEL_OneConnect_Internet_Access_Filter*/
#define RDM_OID_ONE_CONNECT_INTERNET_ACCESS_RULE 122940	/*Device.X_ZYXEL_OneConnect_Internet_Access_Filter.Rule.i*/
#define RDM_OID_ONE_CONNECT_P_C_GENERAL          123048	/*Device.X_ZYXEL_OneConnect_Parental_Control*/
#define RDM_OID_ONE_CONNECT_P_C_RULE             123132	/*Device.X_ZYXEL_OneConnect_Parental_Control.Rule.i*/
#define RDM_OID_ONLINE_F_W_UPGRADE               123360	/*Device.X_ZYXEL_Online_FW_Upgrade*/
#define RDM_OID_LANDING_PAGE                     123588	/*Device.X_ZYXEL_Landing_Page*/
#define RDM_OID_POWER_MGMT                       123672	/*Device.X_ZYXEL_Power_Management*/
#define RDM_OID_POWER_SCHEDULE                   124068	/*Device.X_ZYXEL_Power_Management.PowerSchedule.i*/
#define RDM_OID_ZY_LOOP_GUARD                    124224	/*Device.X_ZYXEL_LOOP_GUARD*/
#define RDM_OID_ZY_PROXIMITY_SENSOR              124332	/*Device.X_ZYXEL_PROXIMITY_SENSOR*/
#define RDM_OID_ZY_RESET_ADMIN                   124392	/*Device.X_ZYXEL_RESET_ADMIN*/
#endif
